spring:
  # datasource:
  #   driver-class-name: org.postgresql.Driver
  #   url: jdbc:postgresql://localhost:5434/postgres
  #   username: postgres
  #   password: 2003

  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  #       dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '{cipher}2a7844d4e7cc3879f15daf05fd1fbf4112de2a70115fe7fbbe8cc184cd0cdd30'
